### ISSUE TITLE
Implement authentication

### ISSUE THREAD

**Issue by cnagourney** [nashenmuck/Network_Server#4]
create is_auth_valid function that takes a username and token and executes 
```
SELECT EXISTS(*) FROM auth_tokens WHERE username=? AND token=?
```

**Comment by dvdmuckle** [comment]
Looks like it may be a little different syntax: https://www.postgresql.org/docs/8.0/static/functions-subquery.html

So something like `EXISTS(SELECT FROM auth_tokens WHERE username=$1 AND tokens=$2)`. Might not be with the `$1` and whatnot, at least that's for `db.Execute()`, even if there's only one value to be inserted/updated/deleted.

**Comment by dvdmuckle** [comment]
Minor tweak, `SELECT EXISTS(SELECT * FROM authtokens WHERE username=$1 AND token=$2)`. This doesn't work, but it... should.

**Comment by dvdmuckle** [comment]
Was an issue with how tokens were stored and printed when a new token was requested. Now resolved in `testing` branch.
